import type { AIKeywordCategory, AIDetection } from '../types.js';

/**
 * AI 工具关键词列表
 */
const AI_TOOL_KEYWORDS: AIKeywordCategory = {
  name: 'AI Tools',
  keywords: [
    // 视频生成工具
    'sora',
    'runway',
    'runwayml',
    'runway gen-2',
    'runway gen-3',
    'pika',
    'pika labs',
    'pikaimalabs',
    'midjourney',
    'mid journey',
    'stable diffusion',
    'stablediffusion',
    'heygen',
    'd-id',
    'did',
    'synthesia',
    'leonardo ai',
    'leonardoai',
    'kaiber',
    'gen-2',
    'gen-3',
    'gen2',
    'gen3',
    'kling',
    'kling ai',
    'vidu',
    'vidu ai',
    'luma',
    'luma dream machine',
    'luma ai',
    'haiper',
    'haiper ai',
    'pictory',
    'synthesia',
    'dall-e',
    'dalle',
    'chatgpt',
    'gpt-4',
    'elevenlabs',
    'eleven labs',
    'murf.ai',
    'murf ai',
    'resemble.ai',
    'descript',
    'wondershare',
    'filmora',
    'capcut',
    'canva ai',
    // 更多工具...
  ],
  weight: 0.9,
};

/**
 * 通用 AI 关键词
 */
const GENERAL_AI_KEYWORDS: AIKeywordCategory = {
  name: 'General AI',
  keywords: [
    'ai generated',
    'ai video',
    'ai-generated',
    'ai-video',
    'aigenerated',
    'aivideo',
    'made with ai',
    'created using ai',
    'powered by ai',
    'ai powered',
    'artificial intelligence',
    'machine learning',
    'neural network',
    'deep learning',
    'generated by ai',
    'ai animation',
    'ai art',
    'ai image',
    'ai content',
    'ai creation',
    'ai generated video',
    'ai generated content',
    'ai filmmaking',
    'ai movie',
    'ai short',
    'ai shorts',
    'ai tool',
    'ai software',
    'ai assistant',
    'ai creator',
    'ai generation',
  ],
  weight: 0.6,
};

/**
 * 所有关键词类别
 */
const KEYWORD_CATEGORIES: AIKeywordCategory[] = [
  AI_TOOL_KEYWORDS,
  GENERAL_AI_KEYWORDS,
];

/**
 * 关键词检测器
 */
export class KeywordDetector {
  private categories: AIKeywordCategory[];

  constructor(customCategories?: AIKeywordCategory[]) {
    this.categories = customCategories || KEYWORD_CATEGORIES;
  }

  /**
   * 检测文本中的 AI 关键词
   */
  detect(text: string): AIDetection {
    const normalizedText = text.toLowerCase();
    const matchedKeywords: string[] = [];
    const detectedTools: string[] = [];
    let maxWeight = 0;

    for (const category of this.categories) {
      for (const keyword of category.keywords) {
        if (normalizedText.includes(keyword.toLowerCase())) {
          matchedKeywords.push(keyword);
          maxWeight = Math.max(maxWeight, category.weight);

          // 如果是 AI 工具类别，记录检测到的工具
          if (category.name === 'AI Tools') {
            detectedTools.push(keyword);
          }
        }
      }
    }

    // 去重
    const uniqueKeywords = [...new Set(matchedKeywords)];
    const uniqueTools = [...new Set(detectedTools)];

    const isAI = uniqueKeywords.length > 0;

    // 计算置信度：基于匹配的关键词数量和权重
    let confidence = 0;
    if (isAI) {
      confidence = Math.min(1, maxWeight + (uniqueKeywords.length * 0.05));
    }

    return {
      isAI,
      method: 'keyword',
      confidence,
      matchedKeywords: uniqueKeywords,
      detectedTool: uniqueTools[0],
      detectedPatterns: [],
    };
  }

  /**
   * 检测标题和描述
   */
  detectFromContent(title: string, description: string): AIDetection {
    const titleDetection = this.detect(title);
    const descDetection = this.detect(description);

    // 合并检测结果
    const allKeywords = [
      ...new Set([
        ...titleDetection.matchedKeywords,
        ...descDetection.matchedKeywords,
      ]),
    ];

    const isAI = titleDetection.isAI || descDetection.isAI;

    // 计算置信度
    let confidence = Math.max(titleDetection.confidence, descDetection.confidence);
    if (titleDetection.isAI && descDetection.isAI) {
      confidence = Math.min(1, confidence + 0.1);
    }

    return {
      isAI,
      method: 'keyword',
      confidence,
      matchedKeywords: allKeywords,
      detectedTool: titleDetection.detectedTool || descDetection.detectedTool,
      detectedPatterns: [],
    };
  }

  /**
   * 获取所有已注册的关键词类别
   */
  getCategories(): AIKeywordCategory[] {
    return this.categories;
  }

  /**
   * 添加自定义关键词类别
   */
  addCategory(category: AIKeywordCategory): void {
    this.categories.push(category);
  }

  /**
   * 获取检测到的 AI 工具名称
   */
  getDetectedTool(detection: AIDetection): string | undefined {
    return detection.detectedTool;
  }

  /**
   * 判断是否为特定 AI 工具
   */
  isSpecificTool(detection: AIDetection, toolName: string): boolean {
    return detection.matchedKeywords.some((k) => {
      const kw = k.toLowerCase();
      return kw === toolName.toLowerCase() || kw.includes(toolName.toLowerCase());
    });
  }
}

/**
 * 导出默认检测器实例
 */
export const keywordDetector = new KeywordDetector();
