import type { PatternRule, AIDetection } from '../types.js';

/**
 * AI 视频模式匹配规则
 */
const AI_PATTERNS: PatternRule[] = [
  {
    name: 'Made with AI',
    pattern: /made\s+(with|by|using)\s+(?:ai|a\.i\.|artificial\s+intelligence)/gi,
    description: '检测 "made with/by/using AI" 模式',
    weight: 0.85,
  },
  {
    name: 'Created with AI',
    pattern: /created\s+(with|by|using)\s+(?:ai|a\.i\.|artificial\s+intelligence)/gi,
    description: '检测 "created with/by/using AI" 模式',
    weight: 0.85,
  },
  {
    name: 'Generated by AI',
    pattern: /(?:ai|a\.i\.|artificial\s+intelligence)\s+(?:generated|created|made|produced)/gi,
    description: '检测 "AI generated/created/made/produced" 模式',
    weight: 0.8,
  },
  {
    name: 'Powered by AI',
    pattern: /powered\s+by\s+(?:ai|a\.i\.|artificial\s+intelligence)/gi,
    description: '检测 "powered by AI" 模式',
    weight: 0.75,
  },
  {
    name: 'AI in Title',
    pattern: /^(?:ai|a\.i\.|artificial\s+intelligence)\s+/gi,
    description: '检测标题以 AI 开头',
    weight: 0.7,
  },
  {
    name: 'AI Animation',
    pattern: /ai\s+(?:animation|anime|cartoon|motion)/gi,
    description: '检测 AI 动画相关模式',
    weight: 0.75,
  },
  {
    name: 'AI Video Generator',
    pattern: /(?:ai|artificial\s+intelligence)\s+(?:video\s+generator|video\s+creator|video\s+maker)/gi,
    description: '检测 AI 视频生成器模式',
    weight: 0.85,
  },
  {
    name: 'Tool Attribution',
    pattern: /(?:made|created|generated|produced)\s+(?:with|using|by)\s+(?:runway|pika|sora|midjourney|heygen|synthesia|leonardo|kaiber|kling|luma|haiper)/gi,
    description: '检测特定 AI 工具署名',
    weight: 0.95,
  },
  {
    name: 'AI Art/Style',
    pattern: /ai\s+(?:art|style|design|creative|artist)/gi,
    description: '检测 AI 艺术相关模式',
    weight: 0.7,
  },
  {
    name: 'No Human Filming',
    pattern: /no\s+(?:human\s+)?(?:filming|camera|shooting|actors)/gi,
    description: '检测无真人拍摄模式',
    weight: 0.6,
  },
  {
    name: 'Fully AI Generated',
    pattern: /(fully|completely|entirely|100%)\s+(?:ai|a\.i\.|artificial\s+intelligence)\s+(?:generated|created|made)/gi,
    description: '检测完全 AI 生成模式',
    weight: 0.9,
  },
  {
    name: 'AI Short/Reel',
    pattern: /ai\s+(?:short|reels|tiktok|youtube\s+shorts)/gi,
    description: '检测 AI 短视频模式',
    weight: 0.7,
  },
];

/**
 * 模式匹配检测器
 */
export class PatternDetector {
  private patterns: PatternRule[];

  constructor(customPatterns?: PatternRule[]) {
    this.patterns = customPatterns || AI_PATTERNS;
  }

  /**
   * 检测文本中的 AI 模式
   */
  detect(text: string): AIDetection {
    const detectedPatterns: string[] = [];
    let maxWeight = 0;

    for (const rule of this.patterns) {
      const matches = text.match(rule.pattern);
      if (matches && matches.length > 0) {
        detectedPatterns.push(rule.name);
        maxWeight = Math.max(maxWeight, rule.weight);
      }
    }

    const isAI = detectedPatterns.length > 0;

    // 置信度基于最大权重和匹配数量
    let confidence = 0;
    if (isAI) {
      confidence = Math.min(1, maxWeight + (detectedPatterns.length * 0.03));
    }

    return {
      isAI,
      method: 'pattern',
      confidence,
      matchedKeywords: [],
      detectedPatterns,
    };
  }

  /**
   * 检测标题和描述
   */
  detectFromContent(title: string, description: string): AIDetection {
    const titleDetection = this.detect(title);
    const descDetection = this.detect(description);

    // 合并检测结果
    const allPatterns = [
      ...new Set([
        ...titleDetection.detectedPatterns,
        ...descDetection.detectedPatterns,
      ]),
    ];

    const isAI = titleDetection.isAI || descDetection.isAI;

    // 计算置信度
    let confidence = Math.max(titleDetection.confidence, descDetection.confidence);
    if (titleDetection.isAI && descDetection.isAI) {
      confidence = Math.min(1, confidence + 0.1);
    }

    return {
      isAI,
      method: 'pattern',
      confidence,
      matchedKeywords: [],
      detectedPatterns: allPatterns,
    };
  }

  /**
   * 获取所有已注册的模式规则
   */
  getPatterns(): PatternRule[] {
    return this.patterns;
  }

  /**
   * 添加自定义模式规则
   */
  addPattern(rule: PatternRule): void {
    this.patterns.push(rule);
  }

  /**
   * 根据名称查找模式
   */
  findPattern(name: string): PatternRule | undefined {
    return this.patterns.find((p) => p.name === name);
  }
}

/**
 * 导出默认检测器实例
 */
export const patternDetector = new PatternDetector();
